Repository O1B3/Hello-iOS, pull requests merged in 2025-08, with the labels that each got.

#2 📦 컬러 에셋 추가
  Hello-iOS/Resources/Assets.xcassets/background.colorset/Contents.json
  Hello-iOS/Resources/Assets.xcassets/cardColor.colorset/Contents.json
  Hello-iOS/Resources/Assets.xcassets/correct.colorset/Contents.json
  Hello-iOS/Resources/Assets.xcassets/main.colorset/Contents.json
  Hello-iOS/Resources/Assets.xcassets/sub.colorset/Contents.json
  Hello-iOS/Resources/Assets.xcassets/wrong.colorset/Contents.json
Labels: 📦 Add

#4 📦 Add: 로고 추가 #3
  Hello-iOS/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Hello-iOS/Resources/Assets.xcassets/AppIcon.appiconset/image 11 1.png
  Hello-iOS/Resources/Assets.xcassets/AppIcon.appiconset/image 11 2.png
  Hello-iOS/Resources/Assets.xcassets/AppIcon.appiconset/image 11 3.png
  Hello-iOS/Resources/Assets.xcassets/chick.imageset/Contents.json
  Hello-iOS/Resources/Assets.xcassets/chick.imageset/chick.png
  Hello-iOS/Resources/Assets.xcassets/egg.imageset/Contents.json
  Hello-iOS/Resources/Assets.xcassets/egg.imageset/egg.png
  Hello-iOS/Resources/Assets.xcassets/hen.imageset/Contents.json
  Hello-iOS/Resources/Assets.xcassets/hen.imageset/hen.png
  Hello-iOS/Resources/Assets.xcassets/logo.imageset/Contents.json
  Hello-iOS/Resources/Assets.xcassets/logo.imageset/logo.png
  Hello-iOS/Resources/Assets.xcassets/phoenix.imageset/Contents.json
  Hello-iOS/Resources/Assets.xcassets/phoenix.imageset/phoenix.png
  Hello-iOS/Resources/Base.lproj/LaunchScreen.storyboard
Labels: 📦 Add

#6 Add: 레벨별 이미지 변경
  Hello-iOS/Presentation/ViewController.swift
  Hello-iOS/Resources/Assets.xcassets/chick.imageset/chick.png
  Hello-iOS/Resources/Assets.xcassets/egg.imageset/egg.png
  Hello-iOS/Resources/Assets.xcassets/hen.imageset/hen.png
  Hello-iOS/Resources/Assets.xcassets/phoenix.imageset/phoenix.png
Labels: 📦 Add

#12 Feat : 하단 탭바 구현
  Hello-iOS/App/SceneDelegate.swift
Labels: ✨ Feat

#16 ✨ Feat: 면접 선택 화면 구성
  Hello-iOS/App/SceneDelegate.swift
  Hello-iOS/Presentation/CommonViews/ShadiwButton.swift
  Hello-iOS/Presentation/Interview/InterviewReactor.swift
  Hello-iOS/Presentation/Interview/InterviewViewController.swift
  Hello-iOS/Presentation/ViewController.swift
Labels: ✨ Feat

#18 Feat/#14 도메인모델 & Realm모델 추가
  .github/PULL_REQUEST_TEMPLATE.md
  Hello-iOS.xcodeproj/project.pbxproj
  Hello-iOS/Model/Attendance.swift
  Hello-iOS/Model/MockInterviewGroup.swift
  Hello-iOS/Model/MockInterviewRecord.swift
  Hello-iOS/Model/UserExperience.swift
  Hello-iOS/Repositories/RealmAttendance.swift
  Hello-iOS/Repositories/RealmMockInterViewGroup.swift
  Hello-iOS/Repositories/RealmMockInterviewRecord.swift
  Hello-iOS/Repositories/RealmUserStatus.swift
  Hello-iOSTests/ModelMappingTest.swift
  Hello-iOSUITests/Hello_iOSUITests.swift
  Hello-iOSUITests/Hello_iOSUITestsLaunchTests.swift
Labels: ✨ Feat

#24 Feat: 면접 진행 화면 및 STT 기능 구현
  Hello-iOS.xcodeproj/project.pbxproj
  Hello-iOS/Base/BaseViewController.swift
  Hello-iOS/Presentation/CommonViews/ShadowButton.swift
  Hello-iOS/Presentation/Interview/InterviewHome/InterviewReactor.swift
  Hello-iOS/Presentation/Interview/InterviewHome/InterviewViewController.swift
  Hello-iOS/Presentation/Interview/InterviewRoom/InterviewRoomReactor.swift
  Hello-iOS/Presentation/Interview/InterviewRoom/InterviewRoomViewController.swift
  Hello-iOS/Presentation/Interview/ResultInterview/ResultInterviewReactor.swift
  Hello-iOS/Presentation/Interview/ResultInterview/ResultInterviewViewController.swift
  Hello-iOS/Presentation/Interview/SelectionInterview/SelectionInterviewReactor.swift
  Hello-iOS/Presentation/Interview/SelectionInterview/SelectionInterviewViewController.swift
  Hello-iOS/Resources/Info.plist
Labels: ✨ Feat

#25 Feat/#23 마이 페이지 데이터 바인딩
  Hello-iOS/App/SceneDelegate.swift
  Hello-iOS/Extensions/RxCocoa++VC.swift
  Hello-iOS/Model/UserExperience.swift
  Hello-iOS/Presentation/MyPage/MyPageInfo/MyPageInfoReactor.swift
  Hello-iOS/Presentation/MyPage/MyPageInfo/MyPageInfoViewController.swift
  Hello-iOS/Services/FetchUserDataService.swift
Labels: ✨ Feat

#28 Feat/#21 단어장 화면 UI 구현
  Hello-iOS/App/SceneDelegate.swift
  Hello-iOS/Model/MockWordBook.swift
  Hello-iOS/Presentation/WordBook/WordBookCell.swift
  Hello-iOS/Presentation/WordBook/WordBookReactor.swift
  Hello-iOS/Presentation/WordBook/WordBookView.swift
  Hello-iOS/Presentation/WordBook/WordBookViewController.swift
  Hello-iOS/Services/LearningService.swift
Labels: ✨ Feat

#32 ✨ 면접 결과 화면 UI 구현
  Hello-iOS/Presentation/CommonViews/RingView.swift
  Hello-iOS/Presentation/Interview/ResultInterview/ResultInterviewViewController.swift
Labels: ✨ Feat

#36 Feat/#31 SupaBase에서 받은 데이터 Realm으로 넣기 + FK 대응필터링
  Hello-iOS.xcodeproj/project.pbxproj
  Hello-iOS/Model/DomainLearingData.swift
  Hello-iOS/Model/MockInterview.swift
  Hello-iOS/Model/MockInterviewGroup.swift
  Hello-iOS/Model/MockInterviewRecord.swift
  Hello-iOS/Repositories/RealmLearningData.swift
  Hello-iOS/Repositories/RealmMockInterViewGroup.swift
  Hello-iOS/Repositories/RealmMockInterview.swift
  Hello-iOS/Repositories/RealmMockInterviewRecord.swift
  Hello-iOSTests/ModelMappingTest.swift
Labels: ✨ Feat, 🔨 Refactor

#39 Feat/#29 단어 학습 UI 구현
  Hello-iOS.xcodeproj/project.pbxproj
  Hello-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Hello-iOS/App/DI/DIContainer.swift
  Hello-iOS/App/SceneDelegate.swift
  Hello-iOS/Presentation/WordBook/WordBookCell.swift
  Hello-iOS/Presentation/WordBook/WordBookReactor.swift
  Hello-iOS/Presentation/WordBook/WordBookView.swift
  Hello-iOS/Presentation/WordBook/WordBookViewController.swift
  Hello-iOS/Presentation/WordBook/WordLearning/ConceptCard.swift
  Hello-iOS/Presentation/WordBook/WordLearning/WordLearningReactor.swift
  Hello-iOS/Presentation/WordBook/WordLearning/WordLearningView.swift
  Hello-iOS/Presentation/WordBook/WordLearning/WordLearningViewController.swift
Labels: ✨ Feat

#43 ✨ Feat: 면접 카테고리 선택 UI 구현
  Hello-iOS/Model/InterviewMode.swift
  Hello-iOS/Presentation/Interview/InterviewHome/InterviewReactor.swift
  Hello-iOS/Presentation/Interview/InterviewHome/InterviewViewController.swift
  Hello-iOS/Presentation/Interview/SelectionInterview/SelectionInterviewReactor.swift
  Hello-iOS/Presentation/Interview/SelectionInterview/SelectionInterviewViewController.swift
Labels: ✨ Feat

#51 🎨 Style: 면접관 이미지 변경
  Hello-iOS/Presentation/Interview/InterviewRoom/InterviewRoomViewController.swift
  Hello-iOS/Resources/Assets.xcassets/Interviewer.imageset/Contents.json
  Hello-iOS/Resources/Assets.xcassets/Interviewer.imageset/Interviewer.png
Labels: 🎨 Style
